<?php 

	echo $this->$err;

?>
<?php
$this->title = "Ajouter un nouveau contrat";
$this->headTitle($this->title);
$t=$this->form;
?>
<div class="center">
<div id="fcontrat">

<form action="<?php echo $this->url(array('controller'=>'contrat','action'=>'ajouter'));?>"
method="post">

 

<div class="select">
<div class="head">Nouvelle contrat
</div>
<table>
<tr>
<td><label ><?php echo $this->form->id->getLabel();?></label></td>
<td><?php echo $this->form->id->renderViewHelper();?></td> 
</tr>
<tr> 
<td><label ><?php echo $this->form->selectC->getLabel();?></label></td>
<td><?php echo $this->form->selectC->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->selectV->getLabel();?></label></td>
<td><?php echo $this->form->selectV->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->date_debut->getLabel();?></label></td>
<td><?php echo $this->form->date_debut->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->date_fin->getLabel();?></label></td>
<td><?php echo $this->form->date_fin->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->prix->getLabel();?></label></td>
<td><?php echo $this->form->prix->renderViewHelper();?></td>
</tr>
<tr>
<td></td>
<td><?php echo $this->form->envoyer->renderViewHelper();?></td>
</tr>
<tr>
<td> &nbsp;<a href="<?php echo $this->url(array('controller'=>'voiture','action'=>'ajouter'));?>">*Novelle voiture</a></td>

<td> &nbsp;<a href="<?php echo $this->url(array('controller'=>'client','action'=>'ajouter'));?>">*Noveau client</a></td>
</tr>
</table>

</div>











</form>

</div>
</div>
