
<?php

$this->title = "Modifier un contrat";
$this->headTitle($this->title);
?>
<div class="center">
<div id="fcontrat">

<form action="<?php echo $this->url(array('controller'=>'contrat','action'=>'modifier'));?>"
method="post">

 

<div class="select">
<div class="head">Modifier contrat
</div>
<table>
<tr>
<td><label ><?php echo $this->form->id->getLabel();?></label></td>
<td><?php echo $this->contrat['id'];?></td> 
</tr>
<tr>
<td><label ><?php echo $this->form->selectC->getLabel();?></label></td>
<td><?php echo $this->contrat['client'];?></td>
<td><?php echo $this->form->selectC->renderViewHelper();?></td>
<td></td>
</tr>
<tr>
<td><label><?php echo $this->form->selectV->getLabel();?></label></td>
<td><?php echo $this->contrat['voiture'];?></td>
<td><?php echo $this->form->selectV->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->date_debut->getLabel();?></label></td>
<td><?php echo $this->form->date_debut->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->date_fin->getLabel();?></label></td>
<td><?php echo $this->form->date_fin->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->prix->getLabel();?></label></td>
<td><?php echo $this->form->prix->renderViewHelper();?></td>
</tr>
<tr>
<td></td>
<td><?php echo $this->form->envoyer->renderViewHelper();?></td>
</tr>

</table>

</div>

</form>














</div>
</div>