<link rel="stylesheet" type="text/css" href="/location/public/css/button.css" />
<div class="center">
<div id="fcontrat">
<form action="" method="post">
<div class="head">Login</div>
<table>
<tr>
<td><label><?php echo $this->form->username->getLabel();?></label></td>
	<td><?php echo $this->form->username->renderViewHelper();?></td>
	</tr>

<tr>
<td>	<label><?php echo $this->form->password->getLabel();?></label></td>
<td>	<?php echo $this->form->password->renderViewHelper();?></td>
</tr>
<tr><td></td>
	<td><?php echo $this->form->login->renderViewHelper();?></td>
</tr>

</form>

</div>
</div>