<?php
$this->title = "Ajouter un nouveau client";
$this->headTitle($this->title);
$t=$this->form;
?>
<div class="center">
<div id="fcontrat">

<form action="<?php echo $this->url(array('controller'=>'client','action'=>'ajouter'));?>"
method="post">

 

<div class="select">
<div class="head">Nouveau client
</div>
<table>
<tr> 
<td><label ><?php echo $this->form->nom->getLabel();?></label></td>
<td><?php echo $this->form->nom->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->prenom->getLabel();?></label></td>
<td><?php echo $this->form->prenom->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->cin->getLabel();?></label></td>
<td><?php echo $this->form->cin->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->Date_naissance->getLabel();?></label></td>
<td><?php echo $this->form->Date_naissance->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->adresse->getLabel();?></label></td>
<td><?php echo $this->form->adresse->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->telephone->getLabel();?></label></td>
<td><?php echo $this->form->telephone->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->passport->getLabel();?></label></td>
<td><?php echo $this->form->passport->renderViewHelper();?></td>
</tr>
<tr>
<td><label><?php echo $this->form->n_permis->getLabel();?></label></td>
<td><?php echo $this->form->n_permis->renderViewHelper();?></td>
</tr>
<tr>
<td></td>
<td><?php echo $this->form->envoyer->renderViewHelper();?></td>
</tr>

</table>

</div>
</form>
</div>
<p><a href="<?php echo $this->url(array('Controller'=>'index','action'=>'index'));?>">&lt;--retour</a></p>
</div>

